"""
src/letter_generator.py — NHS-branded Word document (.docx) letter generator.

Produces four letter types with full NHS letterhead:
  generate_referral_letter()   — GP referral from triage result
  generate_admission_letter()  — Admission confirmation
  generate_diagnosis_letter()  — Diagnosis confirmation to GP
  generate_discharge_letter()  — Discharge summary to GP

All functions return bytes suitable for st.download_button or email attachment.

send_letter_email() sends a letter as a .docx attachment via Gmail SMTP.
"""
import os
from io import BytesIO
from pathlib import Path
from datetime import datetime
import smtplib
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Cm, Inches, Pt, RGBColor
from dotenv import load_dotenv

# ── NHS colours ────────────────────────────────────────────────────────────────
_BLUE   = RGBColor(0x00, 0x5E, 0xB8)
_DARK   = RGBColor(0x00, 0x30, 0x87)
_RED    = RGBColor(0xDA, 0x29, 0x1C)
_AMBER  = RGBColor(0xFF, 0xB8, 0x1C)
_GREEN  = RGBColor(0x00, 0x96, 0x39)
_GREY   = RGBColor(0xAE, 0xB7, 0xBD)
_BLACK  = RGBColor(0x21, 0x21, 0x21)
_WHITE  = RGBColor(0xFF, 0xFF, 0xFF)

_TRIAGE_COLOUR = {"RED": _RED, "AMBER": _AMBER, "GREEN": _GREEN}
_TRIAGE_LABEL  = {"RED": "EMERGENCY", "AMBER": "URGENT", "GREEN": "ROUTINE"}
_TRIAGE_FILL   = {"RED": "FDECEA", "AMBER": "FFF8E1", "GREEN": "E8F5E9"}
_TRIAGE_BORDER = {"RED": "DA291C", "AMBER": "FFB81C", "GREEN": "009639"}

_LOGO_PATH = Path(__file__).parent.parent / "images" / "Logo.png"

_TRUST_NAME    = "Surrey and Sussex Healthcare NHS Trust"
_TRUST_ADDRESS = "East Surrey Hospital, Canada Avenue, Redhill, Surrey, RH1 5RH"
_TRUST_TEL     = "Tel: 01737 768511"
_TRUST_WEB     = "www.surreyandsussex.nhs.uk"
_FOOTER_TEXT   = (
    "Putting people first \u2014 Delivering excellent, accessible healthcare"
)
_DISCLAIMER = (
    "This document was generated by the GP Triage AI system (demo simulation). "
    "In production, this integrates with EPR/PAS and requires clinician sign-off."
)


# ── Document helpers ───────────────────────────────────────────────────────────

def _new_doc() -> Document:
    """Create a blank A4 document with NHS default styles."""
    doc = Document()

    # A4 margins
    for section in doc.sections:
        section.top_margin    = Cm(2.0)
        section.bottom_margin = Cm(2.0)
        section.left_margin   = Cm(2.54)
        section.right_margin  = Cm(2.54)

    # Default paragraph font
    style = doc.styles["Normal"]
    style.font.name = "Arial"
    style.font.size = Pt(11)
    style.font.color.rgb = _BLACK

    return doc


def _run(para, text: str, bold=False, italic=False, size: int = 11,
         colour: RGBColor = None) -> None:
    """Append a formatted run to *para*."""
    run = para.add_run(text)
    run.font.name  = "Arial"
    run.font.size  = Pt(size)
    run.font.bold  = bold
    run.font.italic = italic
    if colour:
        run.font.color.rgb = colour


def _para(doc, text: str = "", bold=False, size: int = 11,
          colour: RGBColor = None, align=WD_ALIGN_PARAGRAPH.LEFT,
          space_before: int = 0, space_after: int = 4) -> None:
    """Add a paragraph with a single run to *doc*."""
    p = doc.add_paragraph()
    p.alignment = align
    p.paragraph_format.space_before = Pt(space_before)
    p.paragraph_format.space_after  = Pt(space_after)
    if text:
        _run(p, text, bold=bold, size=size, colour=colour)
    return p


def _blue_line(doc) -> None:
    """Insert a 2pt NHS-blue horizontal rule."""
    p   = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    bdr = OxmlElement("w:pBdr")
    bot = OxmlElement("w:bottom")
    bot.set(qn("w:val"),   "single")
    bot.set(qn("w:sz"),    "12")      # 1.5pt
    bot.set(qn("w:space"), "1")
    bot.set(qn("w:color"), "005EB8")
    bdr.append(bot)
    pPr.append(bdr)
    p.paragraph_format.space_after  = Pt(8)
    p.paragraph_format.space_before = Pt(0)


def _shaded_para(doc, text: str, fill_hex: str, border_hex: str,
                 colour: RGBColor = None, bold=True, size=12) -> None:
    """Paragraph with coloured background — used for urgency badge."""
    p   = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()

    # Background fill
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"),   "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"),  fill_hex)
    pPr.append(shd)

    # Left border bar
    bdr = OxmlElement("w:pBdr")
    left = OxmlElement("w:left")
    left.set(qn("w:val"),   "single")
    left.set(qn("w:sz"),    "24")
    left.set(qn("w:space"), "4")
    left.set(qn("w:color"), border_hex)
    bdr.append(left)
    pPr.append(bdr)

    p.paragraph_format.space_before = Pt(6)
    p.paragraph_format.space_after  = Pt(6)
    p.paragraph_format.left_indent  = Cm(0.3)
    _run(p, text, bold=bold, size=size, colour=colour or _BLACK)


def _section_heading(doc, text: str) -> None:
    """NHS-blue bold section heading with underline rule."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(10)
    p.paragraph_format.space_after  = Pt(2)
    _run(p, text.upper(), bold=True, size=11, colour=_BLUE)

    # Thin underline via paragraph bottom border
    pPr = p._p.get_or_add_pPr()
    bdr = OxmlElement("w:pBdr")
    bot = OxmlElement("w:bottom")
    bot.set(qn("w:val"),   "single")
    bot.set(qn("w:sz"),    "4")
    bot.set(qn("w:space"), "1")
    bot.set(qn("w:color"), "005EB8")
    bdr.append(bot)
    pPr.append(bdr)


def _kv_table(doc, rows: list[tuple[str, str]]) -> None:
    """Compact 2-column key-value table (no outer borders, light grey shading on keys)."""
    table = doc.add_table(rows=len(rows), cols=2)
    table.style = "Table Grid"
    for i, (key, val) in enumerate(rows):
        cells = table.rows[i].cells

        # Key cell — light blue shading
        kPr = cells[0]._tc.get_or_add_tcPr()
        shd = OxmlElement("w:shd")
        shd.set(qn("w:val"),   "clear")
        shd.set(qn("w:color"), "auto")
        shd.set(qn("w:fill"),  "E8EEF8")
        kPr.append(shd)

        key_para = cells[0].paragraphs[0]
        _run(key_para, key, bold=True, size=10, colour=_DARK)
        cells[0].width = Cm(4.5)

        val_para = cells[1].paragraphs[0]
        _run(val_para, str(val or "—"), size=10)

    doc.add_paragraph().paragraph_format.space_after = Pt(4)


def _add_footer(doc, page_label: str = "") -> None:
    """NHS footer: page number left, trust tagline centre."""
    section = doc.sections[0]
    footer  = section.footer
    # Clear default content
    for p in footer.paragraphs:
        for run in p.runs:
            run.text = ""

    para = footer.paragraphs[0]
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Page number field
    fld_begin  = OxmlElement("w:fldChar"); fld_begin.set(qn("w:fldCharType"),  "begin")
    instr      = OxmlElement("w:instrText"); instr.text = " PAGE "
    fld_sep    = OxmlElement("w:fldChar"); fld_sep.set(qn("w:fldCharType"),    "separate")
    fld_end    = OxmlElement("w:fldChar"); fld_end.set(qn("w:fldCharType"),    "end")
    num_run    = para.add_run()
    num_run._r.append(fld_begin); num_run._r.append(instr)
    num_run._r.append(fld_sep);   num_run._r.append(fld_end)
    num_run.font.size = Pt(9); num_run.font.color.rgb = _GREY

    sep_run = para.add_run("  |  " + _FOOTER_TEXT)
    sep_run.font.size = Pt(9); sep_run.font.color.rgb = _BLUE


# ── Letterhead ─────────────────────────────────────────────────────────────────

def _remove_table_borders(table) -> None:
    """Remove all borders from a docx Table using the lxml API."""
    tbl   = table._tbl
    tblPr = tbl.find(qn("w:tblPr"))
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        tbl.insert(0, tblPr)
    existing = tblPr.find(qn("w:tblBorders"))
    if existing is not None:
        tblPr.remove(existing)
    tbl_borders = OxmlElement("w:tblBorders")
    for side in ("top", "left", "bottom", "right", "insideH", "insideV"):
        el = OxmlElement(f"w:{side}")
        el.set(qn("w:val"),   "none")
        el.set(qn("w:sz"),    "0")
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), "auto")
        tbl_borders.append(el)
    tblPr.append(tbl_borders)


def _add_letterhead(doc) -> None:
    """
    NHS letterhead: 2-column table — trust details left, logo right.
    Followed by an NHS-blue separator line.
    """
    table = doc.add_table(rows=1, cols=2)
    _remove_table_borders(table)

    left_cell  = table.cell(0, 0)
    right_cell = table.cell(0, 1)

    # Trust name
    p1 = left_cell.paragraphs[0]
    p1.paragraph_format.space_after = Pt(2)
    _run(p1, _TRUST_NAME, bold=True, size=13, colour=_BLUE)

    for line in [_TRUST_ADDRESS, _TRUST_TEL, _TRUST_WEB]:
        p = left_cell.add_paragraph()
        p.paragraph_format.space_after = Pt(1)
        _run(p, line, size=9, colour=_DARK)

    # Logo (right-aligned)
    p_logo = right_cell.paragraphs[0]
    p_logo.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    if _LOGO_PATH.exists():
        try:
            run = p_logo.add_run()
            run.add_picture(str(_LOGO_PATH), width=Inches(1.4))
        except Exception:
            _run(p_logo, "NHS", bold=True, size=22, colour=_BLUE)
    else:
        _run(p_logo, "NHS", bold=True, size=22, colour=_BLUE)

    _blue_line(doc)


# ── Public API ─────────────────────────────────────────────────────────────────

def generate_referral_letter(
    nhs_number: str,
    patient_description: str,
    doctor: dict,
    specialty: str,
    imaging: list,
    blood_tests: list,
    triage_result: dict,
    timestamp: str,
) -> bytes:
    """
    Generate an NHS-branded referral letter.

    Args:
        nhs_number:          Patient NHS number.
        patient_description: Free-text patient presentation.
        doctor:              Dict with keys name, role, site.
        specialty:           Referring specialty string.
        imaging:             List of imaging study names.
        blood_tests:         List of blood test names.
        triage_result:       Dict from RAGPipeline (triage_decision, urgency_timeframe, …).
        timestamp:           ISO timestamp string from triage history entry.

    Returns:
        bytes: .docx file content.
    """
    doc = _new_doc()
    _add_letterhead(doc)
    _add_footer(doc)

    triage_lvl  = triage_result.get("triage_decision", "GREEN").upper()
    urgency_txt = triage_result.get("urgency_timeframe", "")
    date_str    = timestamp[:10] if timestamp else datetime.now().strftime("%Y-%m-%d")

    # Date
    _para(doc, datetime.now().strftime("%d %B %Y"), size=11, space_before=8)

    # Urgency badge
    badge_label = _TRIAGE_LABEL.get(triage_lvl, triage_lvl)
    _shaded_para(
        doc,
        f"TRIAGE PRIORITY: {badge_label}  \u2014  {urgency_txt}",
        fill_hex  = _TRIAGE_FILL.get(triage_lvl, "F0F4F5"),
        border_hex= _TRIAGE_BORDER.get(triage_lvl, "AEB7BD"),
        colour    = _TRIAGE_COLOUR.get(triage_lvl, _BLACK),
        size      = 12,
    )

    # Recipient block
    _para(doc, "")
    _para(doc, doctor["name"], bold=True)
    _para(doc, doctor.get("role", ""), space_after=1)
    _para(doc, doctor.get("site", ""), space_after=1)
    _para(doc, "")

    # Re: line
    p_re = doc.add_paragraph()
    p_re.paragraph_format.space_after = Pt(8)
    _run(p_re, "Re: ", bold=True, size=11, colour=_BLUE)
    _run(p_re, f"NHS {nhs_number} \u2014 Referral for {specialty}", size=11)

    # Salutation
    _para(doc, f"Dear {doctor['name']},")
    _para(
        doc,
        "I am writing to refer the above patient for your urgent assessment "
        "following AI-assisted triage via the GP Triage system.",
    )

    # Patient details table
    _section_heading(doc, "Patient Details")
    _kv_table(doc, [
        ("NHS Number",         nhs_number),
        ("Triage Date",        date_str),
        ("Referring System",   "GP Triage AI (Demo)"),
        ("Urgency",            urgency_txt),
        ("AI Confidence",      triage_result.get("confidence", "N/A")),
    ])

    # Presentation
    _section_heading(doc, "Patient Presentation")
    _para(doc, patient_description, space_after=6)

    # Clinical reasoning
    _section_heading(doc, "Clinical Reasoning")
    _para(doc, triage_result.get("clinical_reasoning", ""), space_after=6)

    # Recommended action
    _section_heading(doc, "Recommended Action")
    _para(doc, triage_result.get("recommended_action", ""), space_after=6)

    # Red flags
    red_flags = triage_result.get("red_flags", "None identified")
    _section_heading(doc, "Red Flags")
    flag_colour = _RED if red_flags.lower() != "none identified" else _GREEN
    _para(doc, red_flags, colour=flag_colour, bold=(red_flags.lower() != "none identified"))

    # NICE guideline
    nice = triage_result.get("nice_guideline", "")
    if nice:
        _section_heading(doc, "NICE Guideline Reference")
        _para(doc, nice)

    # Investigations requested
    if imaging or blood_tests:
        _section_heading(doc, "Investigations Requested")
        if imaging:
            p = doc.add_paragraph()
            _run(p, "Imaging:  ", bold=True, size=11)
            _run(p, ", ".join(imaging), size=11)
        if blood_tests:
            p = doc.add_paragraph()
            _run(p, "Blood Tests:  ", bold=True, size=11)
            _run(p, ", ".join(blood_tests), size=11)

    # Sign-off
    _para(doc, "")
    _para(doc, "Yours sincerely,")
    _para(doc, "")
    _para(doc, "GP Triage System (AI-Assisted)", bold=True)
    _para(doc, "Surrey and Sussex Healthcare NHS Trust", size=10, colour=_DARK)
    _para(doc, "GMC Number: [to be completed by authorising clinician]", size=9, colour=_GREY)

    # Disclaimer
    doc.add_paragraph()
    p_disc = doc.add_paragraph()
    pPr = p_disc._p.get_or_add_pPr()
    shd = OxmlElement("w:shd"); shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto"); shd.set(qn("w:fill"), "F0F4F5")
    pPr.append(shd)
    _run(p_disc, _DISCLAIMER, size=9, italic=True, colour=_GREY)

    return _to_bytes(doc)


def generate_admission_letter(nhs_number: str, pathway: dict) -> bytes:
    """Generate an NHS-branded admission confirmation letter."""
    doc = _new_doc()
    _add_letterhead(doc)
    _add_footer(doc)

    s1 = pathway["stages"].get(1,  {}).get("data", {})
    s3 = pathway["stages"].get(3,  {}).get("data", {})
    s5 = pathway["stages"].get(5,  {}).get("data", {})

    _para(doc, datetime.now().strftime("%d %B %Y"), space_before=8)
    _para(doc, "")
    _para(doc, "Re: Admission Confirmation", bold=True, colour=_BLUE, size=12)
    _blue_line(doc)

    _para(doc, f"Dear Patient (NHS: {nhs_number}),")
    _para(
        doc,
        "We are writing to confirm your admission to our hospital. "
        "Please read the following details carefully.",
    )

    _section_heading(doc, "Admission Details")
    _kv_table(doc, [
        ("NHS Number",          nhs_number),
        ("Admission Date",      s5.get("admission_date", "TBC")),
        ("Ward",                s5.get("ward_name", "TBC")),
        ("Bed",                 s5.get("bed_number", "TBC")),
        ("Consultant",          s5.get("admitting_consultant", s3.get("assigned_doctor", "TBC"))),
        ("Admission Type",      s5.get("admission_type", "TBC")),
        ("Hospital",            s5.get("hospital", "East Surrey Hospital")),
    ])

    _section_heading(doc, "What to Bring")
    for item in [
        "Photo ID and NHS number",
        "All current medications (in original packaging)",
        "Glasses, hearing aids, mobility aids if needed",
        "Comfortable clothing and toiletries for your stay",
        "Next-of-kin contact details",
    ]:
        p = doc.add_paragraph(style="List Bullet")
        _run(p, item, size=11)

    _section_heading(doc, "Contact Numbers")
    _kv_table(doc, [
        ("Main Switchboard", "01737 768511"),
        ("Patient Advice",   "01737 768511 ext. 4567"),
        ("NHS 111",          "111"),
    ])

    _para(doc, "")
    _para(doc, "If you have any questions, please do not hesitate to contact us.")
    _para(doc, "")
    _para(doc, "Yours sincerely,")
    _para(doc, "")
    _para(doc, "Admissions Team", bold=True)
    _para(doc, _TRUST_NAME, size=10, colour=_DARK)

    doc.add_paragraph()
    p_disc = doc.add_paragraph()
    _run(p_disc, _DISCLAIMER, size=9, italic=True, colour=_GREY)

    return _to_bytes(doc)


def generate_diagnosis_letter(nhs_number: str, pathway: dict) -> bytes:
    """Generate an NHS-branded diagnosis confirmation letter to GP."""
    doc = _new_doc()
    _add_letterhead(doc)
    _add_footer(doc)

    s1 = pathway["stages"].get(1,  {}).get("data", {})
    s2 = pathway["stages"].get(2,  {}).get("data", {})
    s3 = pathway["stages"].get(3,  {}).get("data", {})
    s6 = pathway["stages"].get(6,  {}).get("data", {})
    doc_name = s3.get("assigned_doctor", "Treating Clinician")

    _para(doc, datetime.now().strftime("%d %B %Y"), space_before=8)
    _para(doc, "")
    _para(doc, "Dear GP,")
    _para(doc, "")

    p_re = doc.add_paragraph()
    p_re.paragraph_format.space_after = Pt(8)
    _run(p_re, "Re: ", bold=True, colour=_BLUE)
    _run(p_re, f"NHS {nhs_number} \u2014 Diagnosis Confirmation")

    _para(
        doc,
        "I am writing to inform you of the confirmed diagnosis for the "
        "above-named patient, referred via the GP Triage system.",
    )

    _section_heading(doc, "Patient & Triage Details")
    _kv_table(doc, [
        ("NHS Number",      nhs_number),
        ("AI Triage",       s2.get("ai_decision", "N/A")),
        ("Urgency",         s2.get("urgency", "N/A")),
        ("Confidence",      s2.get("confidence", "N/A")),
        ("Triage Date",     (pathway.get("created_at") or "")[:10]),
    ])

    _section_heading(doc, "Original Presentation")
    _para(doc, s1.get("patient_description", "Not recorded"), space_after=6)

    _section_heading(doc, "Confirmed Diagnosis")
    _kv_table(doc, [
        ("Diagnosis",           s6.get("confirmed_diagnosis", "Pending")),
        ("ICD-10 Code",         s6.get("icd10_code",           "N/A")),
        ("SNOMED CT Code",      s6.get("snomed_code",           "N/A")),
        ("Diagnosis Date",      s6.get("diagnosis_date",        "N/A")),
        ("Diagnosing Clinician", s6.get("diagnosing_consultant", doc_name)),
        ("Status",              s6.get("diagnosis_status",      "N/A")),
    ])

    _para(doc, "Please update your records accordingly.")
    _para(doc, "")
    _para(doc, "Yours sincerely,")
    _para(doc, "")
    _para(doc, doc_name, bold=True)
    _para(doc, _TRUST_NAME, size=10, colour=_DARK)
    _para(doc, "GMC Number: [to be completed by authorising clinician]", size=9, colour=_GREY)

    doc.add_paragraph()
    p_disc = doc.add_paragraph()
    _run(p_disc, _DISCLAIMER, size=9, italic=True, colour=_GREY)

    return _to_bytes(doc)


def generate_discharge_letter(nhs_number: str, pathway: dict) -> bytes:
    """Generate an NHS-branded discharge summary letter to GP."""
    doc = _new_doc()
    _add_letterhead(doc)
    _add_footer(doc)

    s1  = pathway["stages"].get(1,  {}).get("data", {})
    s2  = pathway["stages"].get(2,  {}).get("data", {})
    s3  = pathway["stages"].get(3,  {}).get("data", {})
    s5  = pathway["stages"].get(5,  {}).get("data", {})
    s6  = pathway["stages"].get(6,  {}).get("data", {})
    s7  = pathway["stages"].get(7,  {}).get("data", {})
    s8  = pathway["stages"].get(8,  {}).get("data", {})
    s9  = pathway["stages"].get(9,  {}).get("data", {})
    s10 = pathway["stages"].get(10, {}).get("data", {})
    doc_name = s3.get("assigned_doctor", "Treating Clinician")

    _para(doc, datetime.now().strftime("%d %B %Y"), space_before=8)
    _para(doc, "")
    _para(doc, "Dear GP,")
    _para(doc, "")

    p_re = doc.add_paragraph()
    p_re.paragraph_format.space_after = Pt(8)
    _run(p_re, "Re: ", bold=True, colour=_BLUE)
    _run(p_re, f"NHS {nhs_number} \u2014 Discharge Summary")

    _para(
        doc,
        "I am writing to inform you that the above patient has been "
        "discharged from our care following the episode summarised below.",
    )

    # Discharge outcome badge
    dc_type = s10.get("discharge_type", "")
    if dc_type:
        fill = "E8F5E9" if dc_type == "Home" else "FFF8E1"
        bdr  = "009639" if dc_type == "Home" else "FFB81C"
        _shaded_para(
            doc,
            f"DISCHARGE TYPE: {dc_type.upper()}",
            fill_hex=fill, border_hex=bdr,
            colour=_GREEN if dc_type == "Home" else _AMBER,
            size=12,
        )

    _section_heading(doc, "Admission Details")
    _kv_table(doc, [
        ("NHS Number",       nhs_number),
        ("Admission Date",   s5.get("admission_date",       "N/A")),
        ("Ward",             s5.get("ward_name",             "N/A")),
        ("Consultant",       s5.get("admitting_consultant",  doc_name)),
        ("Admission Type",   s5.get("admission_type",        "N/A")),
        ("Discharge Date",   s10.get("discharge_date",       "N/A")),
        ("Length of Stay",   s8.get("length_of_stay",        "N/A")),
    ])

    _section_heading(doc, "Original Presentation & Triage")
    _para(doc, s1.get("patient_description", "Not recorded"), space_after=4)
    _kv_table(doc, [
        ("AI Triage Decision", s2.get("ai_decision", "N/A")),
        ("Urgency",            s2.get("urgency",     "N/A")),
    ])

    _section_heading(doc, "Confirmed Diagnosis")
    _kv_table(doc, [
        ("Diagnosis",      s6.get("confirmed_diagnosis", "N/A")),
        ("ICD-10 Code",    s6.get("icd10_code",           "N/A")),
        ("SNOMED CT Code", s6.get("snomed_code",           "N/A")),
    ])

    _section_heading(doc, "Treatment Received")
    _kv_table(doc, [
        ("Treatment Type",    s7.get("treatment_type",    "N/A")),
        ("Procedure",         s7.get("procedure_name",    "N/A")),
        ("Surgeon",           s7.get("operating_surgeon", "N/A")),
        ("Anaesthetic",       s7.get("anaesthetic_type",  "N/A")),
        ("Procedure Date",    s7.get("procedure_date",    "N/A")),
        ("Duration",          f"{s7.get('duration_minutes', 'N/A')} min"),
    ])

    _section_heading(doc, "Outcome")
    _kv_table(doc, [
        ("Outcome",           s8.get("outcome",           "N/A")),
        ("Complications",     s8.get("complications",     "None")),
        ("Follow-up Required", s8.get("follow_up_required", "N/A")),
    ])
    notes = s8.get("outcome_notes", "")
    if notes:
        _para(doc, notes, space_after=4)

    _section_heading(doc, "Aftercare & Follow-Up")
    _kv_table(doc, [
        ("Follow-up Appointment", s9.get("followup_date",    "N/A")),
        ("Follow-up Clinician",   s9.get("followup_doctor",  "N/A")),
        ("Follow-up Location",    s9.get("followup_location","N/A")),
        ("Community Referrals",   ", ".join(s9.get("community_referrals", [])) or "None"),
    ])
    instructions = s9.get("aftercare_instructions", "")
    if instructions:
        _section_heading(doc, "Aftercare Instructions")
        _para(doc, instructions)

    _section_heading(doc, "Discharge Medications")
    meds = s10.get("discharge_medications", "None prescribed")
    _para(doc, meds or "None prescribed")

    if s10.get("discharge_summary"):
        _section_heading(doc, "Discharge Summary")
        _para(doc, s10["discharge_summary"])

    _section_heading(doc, "Emergency Contact Numbers")
    _kv_table(doc, [
        ("East Surrey Hospital", "01737 768511"),
        ("NHS 111",              "111"),
        ("Emergency",            "999"),
    ])

    gp_notified = s10.get("gp_notified", False)
    _para(
        doc,
        f"GP notification status: {'Sent' if gp_notified else 'Pending — please acknowledge receipt.'}",
        bold=not gp_notified,
        colour=_GREEN if gp_notified else _AMBER,
    )

    _para(doc, "")
    _para(doc, "Yours sincerely,")
    _para(doc, "")
    _para(doc, doc_name, bold=True)
    _para(doc, _TRUST_NAME, size=10, colour=_DARK)
    _para(doc, "GMC Number: [to be completed by authorising clinician]", size=9, colour=_GREY)

    doc.add_paragraph()
    p_disc = doc.add_paragraph()
    _run(p_disc, _DISCLAIMER, size=9, italic=True, colour=_GREY)

    return _to_bytes(doc)


# ── Email with attachment ──────────────────────────────────────────────────────

def send_letter_email(
    to_email: str,
    subject: str,
    body: str,
    docx_bytes: bytes,
    filename: str,
) -> tuple[bool, str]:
    """
    Send *docx_bytes* as a .docx email attachment via Gmail SMTP.

    Credentials read from SMTP_EMAIL / SMTP_PASSWORD in .env.
    Returns (success, message).
    """
    load_dotenv()
    user     = os.getenv("SMTP_EMAIL")
    password = os.getenv("SMTP_PASSWORD")
    if not user or not password:
        return False, "SMTP credentials not configured in .env."

    msg            = MIMEMultipart()
    msg["From"]    = user
    msg["To"]      = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    part = MIMEBase(
        "application",
        "vnd.openxmlformats-officedocument.wordprocessingml.document",
    )
    part.set_payload(docx_bytes)
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
    msg.attach(part)

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=10) as srv:
            srv.login(user, password)
            srv.sendmail(user, to_email, msg.as_string())
        return True, f"Sent to {to_email} with attachment {filename}"
    except Exception as exc:
        return False, str(exc)


# ── Internal ───────────────────────────────────────────────────────────────────

def _to_bytes(doc: Document) -> bytes:
    """Save a Document to an in-memory bytes buffer and return the bytes."""
    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.getvalue()
